version: "3.8"

services:
  warp:
    build: .
    container_name: warp-proxy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: always
    ports:
      - "1080:1080"
    environment:
      - ROTATE_INTERVAL=3600
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
        - subnet: "2001:db8:1::/64"
